### ISSUE TITLE
Usage doubt

### ISSUE THREAD

**Issue by mtarin** [haxe-react/haxe-react-native-elements#1]
Hi, i'm trying to use any of the components of this library and i simply cant. 
I've imported the js library and the haxe extern but using the react-native-sample app and adding the component (anyone) to the main view i cant specify any property. 

Example:
<SocialIcon type={'twitter'} />

And in the view context:

```
<View style={styles.container}>
<Text style={styles.text}>
Welcome to Haxe + React Native!!
</Text>
<Text style={styles.text} onPress={goto.bind(1)}>
Goto Scene1
</Text>
<Text style={styles.text} onPress={goto.bind(2)}>
Goto Scene2
</Text>
<Text style={styles.text} onPress={goto.bind(3)}>
Goto Scene3
</Text>
<TextInput
editable = {true}
style={{height: 40, width: 300, borderWidth: 1}}
/>
<SocialIcon type={'twitter'} />
</View>
```

The console result:
src/Main.hx:68: characters 25-32 : Unexpected twitter
src/Main.hx:68: characters 25-32 : Missing ;

Any idea of what could be wrong?

Regards!

**Comment by kevinresol** [comment]
try using a double quote around `twitter`

**Comment by mtarin** [comment]
That works, thanks
